export const ActionTypes = {
    SET_CHARACTERS: 'SET_CHARACTERS',
    SELECTED_CHARACTERS: 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_CHARACTERS: 'REMOVE_SELECTED_CHARACTERS',
    SET_FAVORIES_CHARACTERS: 'SET_FAVORIES_CHARACTERS'
}